using System.Buffers.Binary;
using System.Data;
using System.Drawing.Drawing2D;
using MediaFlux.Models;
using MediaFlux.Services;

namespace MediaFlux;

/// <summary>Read-mostly manager for the existing AI benchmark SQLite records.</summary>
public sealed class AiBenchmarkManagerForm : MediaFluxForm
{
    private readonly AiBenchmarkManagementService _service;
    private readonly Config _config;
    private readonly string _configPath;
    private readonly TableLayoutPanel _root = new() { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 4, Name = "benchmarkRoot", BackColor = Color.FromArgb(243, 246, 249), Padding = new Padding(8, 6, 8, 8) };
    private readonly SplitContainer _lowerSplit = new() { Dock = DockStyle.Fill, Orientation = Orientation.Vertical, Name = "benchmarkDetailsComparisonSplit" };
    private readonly SplitContainer _mainSplit = new() { Dock = DockStyle.Fill, Orientation = Orientation.Horizontal, Name = "benchmarkMainSplit" };
    private readonly DataGridView _grid = new() { Dock = DockStyle.Fill, ReadOnly = true, AllowUserToAddRows = false, AllowUserToDeleteRows = false, MultiSelect = true, SelectionMode = DataGridViewSelectionMode.FullRowSelect, AutoGenerateColumns = true, RowHeadersVisible = false, Name = "benchmarkGrid" };
    private readonly TextBox _filter = new() { Width = 220, PlaceholderText = "Filter GPU, model, backend…", Name = "benchmarkFilter" };
    private readonly Label _status = new() { AutoSize = true, Text = "Ready", Name = "benchmarkStatus" };
    private readonly TableLayoutPanel _summary = new() { Dock = DockStyle.Fill, AutoSize = false, Height = 76, ColumnCount = 7, RowCount = 1, Padding = new Padding(10, 7, 10, 7), Name = "benchmarkSummary" };
    private readonly TableLayoutPanel _details = Inspector("benchmarkDetails");
    private readonly TableLayoutPanel _comparison = new() { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 4, Padding = new Padding(10), Name = "benchmarkComparison" };
    private readonly FpsComparisonChart _chart = new() { Dock = DockStyle.Fill, Name = "benchmarkFpsChart" };
    private IReadOnlyList<AiBenchmarkRecord> _records = Array.Empty<AiBenchmarkRecord>();
    private bool _splitterLayoutInProgress;

    public AiBenchmarkManagerForm(AiBenchmarkManagementService? service = null, Config? config = null, string? configPath = null)
    {
        _service = service ?? new AiBenchmarkManagementService(); _configPath = configPath ?? AppPaths.ConfigFile; _config = config ?? Config.Load(_configPath); Text = "AI Benchmark Manager"; StartPosition = FormStartPosition.CenterParent; BackColor = Color.FromArgb(243, 246, 249);
        MinimumSize = new Size(1100, 700); Size = RestoreSize(); AutoScaleMode = AutoScaleMode.Dpi;
        var commands = new FlowLayoutPanel { Dock = DockStyle.Fill, Height = 48, Padding = new Padding(2, 2, 2, 2), WrapContents = false, Name = "benchmarkCommands", BackColor = Color.White };
        commands.Controls.Add(Button("Run Benchmark", async (_, _) => await RerunSelectedAsync(), "button-play-flat.svg")); commands.Controls.Add(Button("Re-run Selected", async (_, _) => await RerunSelectedAsync(), "return-2-flat.svg")); commands.Controls.Add(Button("Compare Selected", (_, _) => CompareSelected(), "graph-bar-increase.svg")); commands.Controls.Add(Button("Refresh", (_, _) => RefreshRecords(), "arrow-round-left-flat.svg"));
        var importExport = new ToolStripDropDownButton("Import/Export") { Name = "benchmarkCommandImportExport", Image = AiBenchmarkIconService.Get("upload-file-flat.svg", 18, DeviceDpi), ImageScaling = ToolStripItemImageScaling.None, DisplayStyle = ToolStripItemDisplayStyle.ImageAndText }; importExport.DropDownItems.Add("Import…", null, async (_, _) => await ImportAsync()); importExport.DropDownItems.Add("Export Selected…", null, async (_, _) => await ExportAsync(false)); importExport.DropDownItems.Add("Export All…", null, async (_, _) => await ExportAsync(true));
        var maintenance = new ToolStripDropDownButton("More") { Name = "benchmarkCommandMore", Image = AiBenchmarkIconService.Get("bullet-list-flat.svg", 18, DeviceDpi), ImageScaling = ToolStripItemImageScaling.None, DisplayStyle = ToolStripItemDisplayStyle.ImageAndText }; maintenance.DropDownItems.Add("Delete Selected", null, (_, _) => DeleteSelected()); maintenance.DropDownItems.Add("Delete Obsolete", null, (_, _) => DeleteObsolete());
        commands.Controls.Add(new ToolStrip { GripStyle = ToolStripGripStyle.Hidden, AutoSize = true, BackColor = Color.Transparent, Items = { importExport } }); commands.Controls.Add(new ToolStrip { GripStyle = ToolStripGripStyle.Hidden, AutoSize = true, BackColor = Color.Transparent, Items = { maintenance } }); commands.Controls.Add(new Label { Text = "Search", AutoSize = true, Anchor = AnchorStyles.Left, Margin = new Padding(14, 8, 2, 0) }); commands.Controls.Add(_filter); commands.Controls.Add(_status);
        _grid.SelectionChanged += (_, _) => { ShowDetails(); CompareSelected(); }; _lowerSplit.Panel1.BackColor = Color.White; _lowerSplit.Panel2.BackColor = Color.White; _details.BackColor = Color.White; _comparison.BackColor = Color.White; _lowerSplit.Panel1.Controls.Add(LabeledPanel("Details", _details, "benchmarkDetailsLabel", "information-circle-flat.svg")); ConfigureComparisonShell(); _lowerSplit.Panel2.Controls.Add(_comparison); _mainSplit.Panel1.Controls.Add(_grid); _mainSplit.Panel2.Controls.Add(_lowerSplit); _mainSplit.SizeChanged += (_, _) => ApplySplitterLayout(false); _lowerSplit.SizeChanged += (_, _) => ApplySplitterLayout(false); ConfigureRootLayout(commands); Controls.Add(_root); _filter.TextChanged += (_, _) => Bind(); ResizeEnd += (_, _) => PersistNormalSize(); FormClosing += (_, _) => PersistNormalSize(); Shown += (_, _) => { ApplySplitterLayout(true); RefreshRecords(); };
    }

    private static TableLayoutPanel Inspector(string name) => new() { Dock = DockStyle.Fill, AutoScroll = true, AutoSize = false, ColumnCount = 2, Padding = new Padding(10), Name = name };
    private Control LabeledPanel(string title, Control content, string name, string icon) { var panel = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 2, Name = name, Padding = new Padding(8), BackColor = Color.White }; panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32)); panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); panel.Controls.Add(HeaderWithIcon(title, name + "Title", icon), 0, 0); panel.Controls.Add(content, 0, 1); return panel; }
    private static Label SectionTitle(string text, string name) => new() { Text = text, Dock = DockStyle.Top, Height = 28, Name = name, Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), ForeColor = Color.FromArgb(55, 65, 81), Padding = new Padding(2, 4, 2, 2) };
    private Control HeaderWithIcon(string text, string name, string icon) { var header = new Panel { Dock = DockStyle.Fill, BackColor = Color.White, Name = name + "Host" }; header.Controls.Add(new Label { Text = text, Dock = DockStyle.Fill, Name = name, Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), ForeColor = Color.FromArgb(30, 41, 59), TextAlign = ContentAlignment.MiddleLeft, Padding = new Padding(31, 0, 0, 0) }); header.Controls.Add(IconBox(icon, 24, name + "Icon")); return header; }
    private Button Button(string text, EventHandler click, string icon) { var button = new Button { Text = text, AutoSize = true, Height = 32, Name = "benchmarkCommand" + text.Replace(" ", ""), Margin = new Padding(2, 0, 2, 0), Image = AiBenchmarkIconService.Get(icon, 18, DeviceDpi), ImageAlign = ContentAlignment.MiddleLeft, TextImageRelation = TextImageRelation.ImageBeforeText, Padding = new Padding(7, 0, 7, 0), FlatStyle = FlatStyle.Standard, UseVisualStyleBackColor = true }; button.Click += click; return button; }
    private PictureBox IconBox(string icon, int logicalSize, string name) { int size = Scale(logicalSize); return new PictureBox { Image = AiBenchmarkIconService.Get(icon, logicalSize, DeviceDpi), Size = new Size(size, size), Location = new Point(3, Math.Max(0, (32 - size) / 2)), SizeMode = PictureBoxSizeMode.CenterImage, Name = name, BackColor = Color.FromArgb(239, 246, 255), Padding = new Padding(Math.Max(2, size / 6)) }; }
    private void ApplySplitterLayout(bool preferred) { if (_splitterLayoutInProgress || IsDisposed) return; _splitterLayoutInProgress = true; try { int mainAvailable = _mainSplit.ClientSize.Height - _mainSplit.SplitterWidth; int lowerAvailable = _lowerSplit.ClientSize.Width - _lowerSplit.SplitterWidth; ConfigureSplitter(_mainSplit, Scale(200), Scale(250), preferred && mainAvailable > 0 ? (int)(mainAvailable * .50) : _mainSplit.SplitterDistance, preferred); ConfigureSplitter(_lowerSplit, Scale(300), Scale(300), preferred && lowerAvailable > 0 ? lowerAvailable / 2 : _lowerSplit.SplitterDistance, preferred); } finally { _splitterLayoutInProgress = false; } }
    private void ConfigureSplitter(SplitContainer splitter, int min1, int min2, int target, bool preferred) { int available = (splitter.Orientation == Orientation.Vertical ? splitter.ClientSize.Width : splitter.ClientSize.Height) - splitter.SplitterWidth; if (available < min1 + min2) return; splitter.Panel1MinSize = min1; splitter.Panel2MinSize = min2; splitter.SplitterDistance = Math.Clamp(preferred ? target : splitter.SplitterDistance, min1, available - min2); }
    private int Scale(int value) => (int)Math.Round(value * DeviceDpi / 96d);
    private Size RestoreSize() { int width = _config.AiBenchmarkManagerWindowWidth; int height = _config.AiBenchmarkManagerWindowHeight; if (width <= 0 || height <= 0) return new Size(1500, 950); return new Size(Math.Clamp(width, 1100, 4000), Math.Clamp(height, 700, 3000)); }
    private void PersistNormalSize() { if (WindowState != FormWindowState.Normal || IsDisposed) return; _config.AiBenchmarkManagerWindowWidth = Math.Max(MinimumSize.Width, Width); _config.AiBenchmarkManagerWindowHeight = Math.Max(MinimumSize.Height, Height); try { _config.Save(_configPath); } catch (Exception ex) { ErrorLogService.Append(AppPaths.UserDataDirectory, "Save AI Benchmark Manager window size failed", exception: ex); } }

    private void ConfigureRootLayout(Control commands)
    { _root.RowStyles.Add(new RowStyle(SizeType.Absolute, Scale(48))); _root.RowStyles.Add(new RowStyle(SizeType.Absolute, Scale(84))); _root.RowStyles.Add(new RowStyle(SizeType.Absolute, Scale(8))); _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); _root.Controls.Add(commands, 0, 0); _root.Controls.Add(_summary, 0, 1); _root.Controls.Add(new Panel { Dock = DockStyle.Fill, BackColor = Color.FromArgb(243, 246, 249), Name = "benchmarkSummaryGap" }, 0, 2); _root.Controls.Add(_mainSplit, 0, 3); }

    private void ConfigureComparisonShell()
    { _comparison.RowStyles.Add(new RowStyle(SizeType.AutoSize)); _comparison.RowStyles.Add(new RowStyle(SizeType.AutoSize)); _comparison.RowStyles.Add(new RowStyle(SizeType.AutoSize)); _comparison.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); _comparison.Controls.Add(HeaderWithIcon("Comparison (0 selected)", "benchmarkComparisonLabel", "graph-dot-flat.svg"), 0, 0); _comparison.Controls.Add(new Label { Text = "First selected benchmark is used as the baseline.", AutoSize = true, ForeColor = Color.FromArgb(100, 116, 139), Name = "benchmarkComparisonHint", Padding = new Padding(2, 0, 2, 6) }, 0, 1); _comparison.Controls.Add(new Label { Text = "Select two or more benchmarks to compare.", AutoSize = true, Name = "benchmarkComparisonEmpty", Padding = new Padding(2, 8, 2, 8) }, 0, 2); _comparison.Controls.Add(_chart, 0, 3); }

    private void RefreshRecords() { _records = _service.List(); Bind(); _status.Text = _records.Count == 0 ? "No benchmark results." : $"{_records.Count:N0} benchmark result(s)"; }
    private void Bind()
    {
        string filter = _filter.Text.Trim(); AiRuntimeTelemetrySnapshot runtime = AiRuntimeTelemetryService.Shared.GetSnapshot(); var visible = _records.Where(r => string.IsNullOrWhiteSpace(filter) || Search(r, filter)).ToArray(); var best = BestIds(visible); var table = new DataTable();
        foreach (var column in new[] { "Id", "Date/time", "GPU", "Backend", "Provider", "Model", "Scale", "Tile", "Threads", "Precision", "Average FPS", "Status", "Best" }) { DataColumn dataColumn = table.Columns.Add(column); if (column is "Id") dataColumn.DataType = typeof(long); else if (column is "Average FPS") dataColumn.DataType = typeof(double); }
        foreach (AiBenchmarkRecord record in visible) { var e = record.Entry; string status = IsActive(runtime, e) ? "Active" : e.IsStable && e.FramesPerSecond > 0 ? "Validated" : e.IsStable ? "Failed" : "Obsolete"; table.Rows.Add(record.Id, e.Timestamp.LocalDateTime, e.Key.GpuIdentity, e.Key.BackendId, Provider(e.Key.BackendId), e.Key.Model, e.Key.Scale + "x", e.Configuration.TileDisplay, e.Configuration.ThreadsDisplay, e.Key.Precision, e.FramesPerSecond, status, best.Contains(record.Id) ? "Best" : ""); }
        _grid.DataSource = table; ConfigureGrid(); UpdateSummary(visible); ShowDetails();
    }
    private void ConfigureGrid() { if (_grid.Columns.Contains("Id")) _grid.Columns["Id"].Visible = false; _grid.BackgroundColor = Color.White; _grid.BorderStyle = BorderStyle.FixedSingle; _grid.ColumnHeadersHeight = 32; _grid.RowTemplate.Height = 27; foreach (DataGridViewColumn c in _grid.Columns) { c.SortMode = DataGridViewColumnSortMode.Automatic; c.AutoSizeMode = DataGridViewAutoSizeColumnMode.None; c.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft; } _grid.Columns["Date/time"].Width = 128; _grid.Columns["GPU"].AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill; _grid.Columns["GPU"].FillWeight = 145; _grid.Columns["Backend"].Width = 95; _grid.Columns["Provider"].Width = 75; _grid.Columns["Model"].AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill; _grid.Columns["Model"].FillWeight = 125; _grid.Columns["Scale"].Width = 55; _grid.Columns["Tile"].Width = 65; _grid.Columns["Threads"].Width = 75; _grid.Columns["Precision"].Width = 72; _grid.Columns["Average FPS"].Width = 88; _grid.Columns["Status"].Width = 82; _grid.Columns["Best"].Width = 55; _grid.Columns["Date/time"].DefaultCellStyle.Format = "g"; _grid.Columns["Average FPS"].DefaultCellStyle.Format = "0.00"; foreach (string name in new[] { "Scale", "Tile", "Threads", "Average FPS" }) _grid.Columns[name].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252); _grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(30, 105, 180); _grid.ColumnHeadersDefaultCellStyle.Font = new Font(_grid.Font, FontStyle.Bold); _grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(226, 232, 240); _grid.EnableHeadersVisualStyles = false; }
    private void UpdateSummary(IReadOnlyList<AiBenchmarkRecord> visible) { _summary.Controls.Clear(); _summary.ColumnStyles.Clear(); foreach (float weight in new[] { 9f, 11f, 21f, 12f, 18f, 9f, 10f }) _summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, weight)); foreach (var item in new[] { ("Results", visible.Count.ToString("N0"), "database-flat.svg"), ("Best valid FPS", visible.Where(r => r.Entry.IsStable && r.Entry.FramesPerSecond > 0).Select(r => r.Entry.FramesPerSecond).DefaultIfEmpty().Max().ToString("0.00"), "graph-bar-increase-flat.svg"), ("GPU", Common(visible.Select(r => r.Entry.Key.GpuIdentity)), "computer-chip-1-flat.svg"), ("Backend", Common(visible.Select(r => r.Entry.Key.BackendId)), "cog.svg"), ("Model", Common(visible.Select(r => r.Entry.Key.Model)), "align-front-1-flat.svg"), ("Scale", Common(visible.Select(r => r.Entry.Key.Scale + "x")), "arrow-shrink-diagonal-1-flat.svg"), ("Precision", Common(visible.Select(r => r.Entry.Key.Precision)), "computer-chip-2-flat.svg") }) { string value = string.IsNullOrEmpty(item.Item2) ? "Unavailable" : item.Item2; _summary.Controls.Add(SummaryTile(item.Item1, value, item.Item3), _summary.Controls.Count, 0); } }
    private Control SummaryTile(string title, string value, string icon) { string key = title.Replace(" ", ""); var tile = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.White, CellBorderStyle = TableLayoutPanelCellBorderStyle.Single, ColumnCount = 2, RowCount = 2, Name = "summary" + key, Text = $"{title}\n{value}", Padding = new Padding(7, 5, 7, 5), Margin = new Padding(3, 0, 3, 0) }; tile.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, Scale(34))); tile.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); tile.RowStyles.Add(new RowStyle(SizeType.Absolute, Scale(22))); tile.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); PictureBox iconBox = IconBox(icon, 25, "summary" + key + "Icon"); iconBox.Dock = DockStyle.Fill; tile.Controls.Add(iconBox, 0, 0); tile.SetRowSpan(iconBox, 2); tile.Controls.Add(new Label { Text = title, AutoSize = false, Dock = DockStyle.Fill, Name = "summary" + key + "Title", ForeColor = Color.FromArgb(71, 85, 105), AutoEllipsis = true, TextAlign = ContentAlignment.MiddleLeft }, 1, 0); tile.Controls.Add(new Label { Text = value, AutoSize = false, Dock = DockStyle.Fill, Name = "summary" + key + "Value", Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), ForeColor = Color.FromArgb(30, 41, 59), AutoEllipsis = true, TextAlign = ContentAlignment.MiddleLeft }, 1, 1); return tile; }
    private static string Common(IEnumerable<string> values) { string[] distinct = values.Where(v => !string.IsNullOrWhiteSpace(v)).Distinct(StringComparer.OrdinalIgnoreCase).ToArray(); return distinct.Length == 0 ? "Unavailable" : distinct.Length == 1 ? distinct[0] : "Multiple"; }
    private static bool Search(AiBenchmarkRecord r, string value) => new[] { r.Entry.Key.GpuIdentity, r.Entry.Key.BackendId, r.Entry.Key.Model, r.Entry.Key.DriverVersion, r.Entry.Key.ResolutionClass, r.Entry.Key.Precision }.Any(x => x.Contains(value, StringComparison.OrdinalIgnoreCase));
    private static bool IsActive(AiRuntimeTelemetrySnapshot runtime, AiBenchmarkDatabaseEntry e) => runtime.IsActive && runtime.Backend.Equals(e.Key.BackendId, StringComparison.OrdinalIgnoreCase) && runtime.Model.Equals(e.Key.Model, StringComparison.OrdinalIgnoreCase) && (int)runtime.Scale == e.Key.Scale && runtime.GpuName.Equals(e.Key.GpuIdentity, StringComparison.OrdinalIgnoreCase) && runtime.DriverVersion.Equals(e.Key.DriverVersion, StringComparison.OrdinalIgnoreCase);
    private IReadOnlyList<AiBenchmarkRecord> Selected() => _grid.SelectedRows.Cast<DataGridViewRow>().Select(r => r.Cells["Id"].Value).OfType<long>().Select(id => _records.FirstOrDefault(r => r.Id == id)).Where(r => r is not null).Cast<AiBenchmarkRecord>().DistinctBy(r => r.Id).ToArray();

    private void ShowDetails() { _details.SuspendLayout(); _details.Controls.Clear(); AiBenchmarkRecord? selected = Selected().FirstOrDefault(); if (selected is null) { _details.Controls.Add(new Label { Text = "Select a benchmark to view its stored metadata.", AutoSize = true }); _details.ResumeLayout(); return; } var e = selected.Entry; int row = 0; AddSection(_details, "Hardware", ref row); AddPair(_details, "GPU", e.Key.GpuIdentity, ref row); AddPair(_details, "Driver", e.Key.DriverVersion, ref row); AddPair(_details, "Peak VRAM", Bytes(e.PeakVramBytes), ref row); AddPair(_details, "CPU", "Unavailable", ref row); AddSection(_details, "Runtime", ref row); AddPair(_details, "Backend", e.Key.BackendId, ref row); AddPair(_details, "Provider", Provider(e.Key.BackendId), ref row); AddPair(_details, "Model", e.Key.Model, ref row); AddPair(_details, "Scale", e.Key.Scale + "x", ref row); AddPair(_details, "Tile", e.Configuration.TileDisplay, ref row); AddPair(_details, "Threads", e.Configuration.ThreadsDisplay, ref row); AddPair(_details, "Precision", e.Key.Precision, ref row); AddPair(_details, "Resolution", e.Key.ResolutionClass, ref row); AddSection(_details, "Performance", ref row); AddPair(_details, "Average FPS", e.FramesPerSecond.ToString("0.00"), ref row); AddPair(_details, "Peak FPS", "Unavailable", ref row); AddPair(_details, "Benchmark duration", "Unavailable", ref row); AddPair(_details, "Timestamp", e.Timestamp.LocalDateTime.ToString("g"), ref row); AddPair(_details, "Status", e.IsStable && e.FramesPerSecond > 0 ? "Validated" : "Obsolete", ref row); AddPair(_details, "Source", "SQLite benchmark database", ref row); AddPair(_details, "Summary", string.IsNullOrWhiteSpace(e.Summary) ? "Unavailable" : e.Summary, ref row); _details.ResumeLayout(); }
    private static void AddSection(TableLayoutPanel table, string title, ref int row) { table.RowStyles.Add(new RowStyle(SizeType.AutoSize)); var label = SectionTitle(title, ""); table.Controls.Add(label, 0, row++); table.SetColumnSpan(label, 2); }
    private static void AddPair(TableLayoutPanel table, string label, string value, ref int row) { table.RowStyles.Add(new RowStyle(SizeType.Absolute, 19)); table.Controls.Add(new Label { Text = label, AutoSize = false, Dock = DockStyle.Fill, Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), Margin = Padding.Empty, TextAlign = ContentAlignment.MiddleLeft }, 0, row); table.Controls.Add(new Label { Text = value, AutoSize = false, Dock = DockStyle.Fill, Margin = Padding.Empty, AutoEllipsis = true, TextAlign = ContentAlignment.MiddleLeft }, 1, row++); table.ColumnStyles.Clear(); table.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120)); table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); }

    private void CompareSelected()
    {
        AiBenchmarkRecord[] records = Selected().ToArray();
        Control comparisonHeader = _comparison.GetControlFromPosition(0, 0)!; comparisonHeader.Controls.Find("benchmarkComparisonLabel", false).OfType<Label>().Single().Text = $"Comparison ({records.Length} selected)";
        Control? oldTable = _comparison.GetControlFromPosition(0, 2); if (oldTable is not null) { _comparison.Controls.Remove(oldTable); oldTable.Dispose(); }
        if (records.Length < 2) { _chart.SetData(Array.Empty<(string, double)>()); _comparison.Controls.Add(new Label { Text = "Select two or more benchmarks to compare.", AutoSize = true, Name = "benchmarkComparisonEmpty", Padding = new Padding(2, 8, 2, 8) }, 0, 2); return; }
        var table = new TableLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, ColumnCount = records.Length + 2, RowCount = 1, CellBorderStyle = TableLayoutPanelCellBorderStyle.Single, Name = "benchmarkComparisonTable", BackColor = Color.White }; for (int c = 0; c < table.ColumnCount; c++) table.ColumnStyles.Add(new ColumnStyle(c == 0 ? SizeType.Percent : SizeType.AutoSize, c == 0 ? 30 : 0));
        string[] headers = new[] { "Metric" }.Concat(records.Select((r, i) => i == 0 ? "Baseline" : records.Length == 2 ? "Selected" : $"Selected {i}" )).Append("Difference").ToArray(); for (int c = 0; c < headers.Length; c++) table.Controls.Add(new Label { Text = headers[c], AutoSize = true, Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), Padding = new Padding(7, 5, 7, 5), BackColor = Color.FromArgb(241, 245, 249) }, c, 0);
        var baseline = records[0].Entry; AddComparisonRow(table, "Average FPS", records.Select(r => r.Entry.FramesPerSecond.ToString("0.00") + " FPS").ToArray(), PercentageDifference(baseline.FramesPerSecond, records[1].Entry.FramesPerSecond)); AddComparisonRow(table, "Tile size", records.Select(r => r.Entry.Configuration.TileDisplay).ToArray(), CategoricalDifference(baseline.Configuration.TileDisplay, records[1].Entry.Configuration.TileDisplay)); AddComparisonRow(table, "Threads", records.Select(r => r.Entry.Configuration.ThreadsDisplay).ToArray(), CategoricalDifference(baseline.Configuration.ThreadsDisplay, records[1].Entry.Configuration.ThreadsDisplay)); AddComparisonRow(table, "Precision", records.Select(r => r.Entry.Key.Precision).ToArray(), CategoricalDifference(baseline.Key.Precision, records[1].Entry.Key.Precision)); AddComparisonRow(table, "Peak VRAM", records.Select(r => Bytes(r.Entry.PeakVramBytes)).ToArray(), CategoricalDifference(Bytes(baseline.PeakVramBytes), Bytes(records[1].Entry.PeakVramBytes))); AddComparisonRow(table, "Status", records.Select(r => r.Entry.IsStable && r.Entry.FramesPerSecond > 0 ? "Validated" : "Obsolete").ToArray(), CategoricalDifference(baseline.IsStable && baseline.FramesPerSecond > 0 ? "Validated" : "Obsolete", records[1].Entry.IsStable && records[1].Entry.FramesPerSecond > 0 ? "Validated" : "Obsolete")); _comparison.Controls.Add(table, 0, 2); _chart.SetData(records.Select((r, i) => ($"{i + 1}: {r.Entry.Key.Model} {r.Entry.Key.Scale}x", r.Entry.FramesPerSecond)).ToArray());
    }
    private static void AddComparisonRow(TableLayoutPanel table, string metric, string[] values, string difference) { int row = table.RowCount++; table.RowStyles.Add(new RowStyle(SizeType.AutoSize)); table.Controls.Add(new Label { Text = metric, AutoSize = true, Font = new Font(SystemFonts.DefaultFont, FontStyle.Bold), Padding = new Padding(5) }, 0, row); for (int i = 0; i < values.Length; i++) table.Controls.Add(new Label { Text = values[i], AutoSize = true, Padding = new Padding(5) }, i + 1, row); table.Controls.Add(new Label { Text = difference, AutoSize = true, Padding = new Padding(5) }, values.Length + 1, row); }
    internal static string PercentageDifference(double baseline, double selected) => baseline == 0 ? (selected == 0 ? "Same" : "Unavailable") : $"{(selected - baseline) / Math.Abs(baseline) * 100:+0.##;-0.##;0}%";
    private static string CategoricalDifference(string baseline, string selected) => baseline.Equals(selected, StringComparison.OrdinalIgnoreCase) ? "Same" : "Changed";
    internal static HashSet<long> BestIds(IEnumerable<AiBenchmarkRecord> records) { var rows = records.Where(r => r.Entry.IsStable && r.Entry.FramesPerSecond > 0).GroupBy(r => new { r.Entry.Key.GpuIdentity, r.Entry.Key.BackendId, r.Entry.Key.BackendIdentity, r.Entry.Key.Model, r.Entry.Key.Scale, r.Entry.Key.Precision, r.Entry.Key.ResolutionClass }); return rows.SelectMany(g => g.Where(r => r.Entry.FramesPerSecond == g.Max(x => x.Entry.FramesPerSecond)).Select(r => r.Id)).ToHashSet(); }
    private void DeleteSelected() { AiBenchmarkRecord[] records = Selected().ToArray(); if (records.Length == 0) return; if (MessageBox.Show(this, $"Delete {records.Length} selected benchmark(s)? Tuning cache files are not changed.", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes) return; _status.Text = $"Deleted {_service.DeleteSelected(records)} benchmark(s)."; RefreshRecords(); }
    private void DeleteObsolete() { if (MessageBox.Show(this, "Delete failed/obsolete benchmark rows? Validated results and tuning cache files are not changed.", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes) return; _status.Text = $"Deleted {_service.DeleteObsolete()} obsolete benchmark(s)."; RefreshRecords(); }
    private async Task ExportAsync(bool all) { AiBenchmarkRecord[] records = (all ? _records : Selected()).ToArray(); if (records.Length == 0) { _status.Text = "No benchmark records selected."; return; } using var dialog = new SaveFileDialog { Filter = "MediaFlux AI benchmarks (*.mfai-benchmarks.json)|*.mfai-benchmarks.json", FileName = "mediaflux-ai-benchmarks.json" }; if (dialog.ShowDialog(this) != DialogResult.OK) return; await _service.ExportAsync(dialog.FileName, records); _status.Text = $"Exported {records.Length} benchmark(s)."; }
    private async Task ImportAsync() { using var dialog = new OpenFileDialog { Filter = "MediaFlux AI benchmarks (*.mfai-benchmarks.json;*.json)|*.mfai-benchmarks.json;*.json" }; if (dialog.ShowDialog(this) != DialogResult.OK) return; AiBenchmarkImportResult result = await _service.ImportAsync(dialog.FileName); _status.Text = $"{result.Message} Imported: {result.Imported}; rejected: {result.Rejected}."; RefreshRecords(); }
    private async Task RerunSelectedAsync() { AiBenchmarkRecord? record = Selected().FirstOrDefault(); if (record is null) { _status.Text = "Select a benchmark to re-run."; return; } using var dialog = new FolderBrowserDialog { Description = "Choose a folder containing at least 120 extracted PNG preview frames." }; if (dialog.ShowDialog(this) != DialogResult.OK) return; string[] frames = Directory.EnumerateFiles(dialog.SelectedPath, "*.png").OrderBy(path => path, StringComparer.OrdinalIgnoreCase).ToArray(); if (frames.Length < AiBackendBenchmarkService.DefaultFrameCount) { _status.Text = "A re-run requires at least 120 PNG preview frames."; return; } if (!TryReadPngSize(frames[0], out int width, out int height)) { _status.Text = "The selected preview frames are not readable PNG files."; return; } _status.Text = "Re-running benchmark…"; Enabled = false; try { AiBenchmarkDatabaseEntry entry = record.Entry; var settings = new VideoRestorationSettings { AiMode = AiRestorationMode.General, AiModelId = entry.Key.Model, AiScale = (AiRestorationScale)entry.Key.Scale, AiBackendSelection = AiBackendSelection.NcnnVulkan }; IAiRestorationBackend backend = await new AiBackendManager(AppPaths.InstallDirectory).SelectAsync(settings); AiBackendBenchmarkResult result = await new AiBackendBenchmarkService(AppPaths.AiBenchmarkRerunsDirectory).RunAsync(new(backend, settings, frames, width, height)); _status.Text = $"Re-run completed: {result.EffectiveFramesPerSecond:0.00} FPS."; RefreshRecords(); } catch (Exception ex) { _status.Text = "Re-run failed: " + ex.Message; } finally { Enabled = true; } }
    private static bool TryReadPngSize(string path, out int width, out int height) { width = height = 0; try { byte[] bytes = File.ReadAllBytes(path); if (bytes.Length < 24 || bytes[0] != 137 || bytes[1] != 80 || bytes[2] != 78 || bytes[3] != 71) return false; width = BinaryPrimitives.ReadInt32BigEndian(bytes.AsSpan(16, 4)); height = BinaryPrimitives.ReadInt32BigEndian(bytes.AsSpan(20, 4)); return width > 0 && height > 0; } catch { return false; } }
    private static string Provider(string backend) => backend.Equals("ncnn-vulkan", StringComparison.OrdinalIgnoreCase) ? "NCNN" : backend;
    private static string Bytes(long? value) => value is long bytes ? (bytes / 1073741824d).ToString("0.##") + " GiB" : "Unavailable";
}

internal sealed class FpsComparisonChart : Control
{
    private IReadOnlyList<(string Label, double Fps)> _data = Array.Empty<(string, double)>();
    public FpsComparisonChart() { DoubleBuffered = true; ResizeRedraw = true; BackColor = Color.White; }
    public void SetData(IReadOnlyList<(string Label, double Fps)> data) { _data = data; Invalidate(); }
    protected override void OnPaint(PaintEventArgs e) { base.OnPaint(e); e.Graphics.SmoothingMode = SmoothingMode.AntiAlias; using var background = new SolidBrush(Color.White); using var border = new Pen(Color.FromArgb(203, 213, 225)); e.Graphics.FillRectangle(background, ClientRectangle); e.Graphics.DrawRectangle(border, 0, 0, Math.Max(0, Width - 1), Math.Max(0, Height - 1)); using var text = new SolidBrush(Color.FromArgb(55, 65, 81)); using var muted = new SolidBrush(Color.FromArgb(100, 116, 139)); using var grid = new Pen(Color.FromArgb(226, 232, 240)); e.Graphics.DrawString("Average FPS Comparison", new Font(Font, FontStyle.Bold), text, 10, 8); if (_data.Count == 0) { e.Graphics.DrawString("Select two or more benchmarks to see relative performance.", Font, muted, 10, 34); return; } double max = Math.Max(1, _data.Max(x => Math.Max(0, x.Fps))); int left = Math.Min(190, Math.Max(120, Width / 3)), top = 34, footer = 22, width = Math.Max(1, ClientSize.Width - left - 18), usableHeight = Math.Max(20, Height - top - footer); using var brush = new SolidBrush(Color.FromArgb(37, 99, 235)); for (int i = 0; i < _data.Count; i++) { int y = top + i * Math.Max(22, usableHeight / _data.Count); int bar = (int)Math.Round(Math.Max(0, _data[i].Fps) / max * Math.Max(1, width - 45)); e.Graphics.DrawString(Trim(_data[i].Label), Font, text, 8, y); e.Graphics.DrawLine(grid, left, y + 19, left + width, y + 19); e.Graphics.FillRectangle(brush, left, y + 2, bar, 15); int valueX = Math.Min(left + bar + 5, Math.Max(left, left + width - 40)); e.Graphics.DrawString(_data[i].Fps.ToString("0.00"), Font, text, valueX, y); } e.Graphics.DrawString("Average FPS (higher is better)", Font, muted, left, Height - footer + 2); }
    private string Trim(string value) => value.Length <= 22 ? value : value[..21] + "…";
}
