using System.Globalization;
using MediaFlux.Models;

namespace MediaFlux.Services;
/// <summary>Bounded, read-only timing characterization. Current frame AI remains deliberately CFR-only.</summary>
public sealed class SourceTimingAnalysisService
{
    private readonly string _ffprobePath; private readonly IMediaToolProcessRunner _runner; private readonly Action<string>? _log;
    public SourceTimingAnalysisService(string ffprobePath, IMediaToolProcessRunner? runner = null, Action<string>? log = null) { _ffprobePath = ffprobePath; _runner = runner ?? new MediaToolProcessRunner(); _log = log; }
    public SourceTimingAnalysis Analyze(SourceTimingEvidence e)
    {
        TimingWindowEvidence[] samples = (e.Windows is { Count: > 0 } ? e.Windows : new[] { new TimingWindowEvidence(0, e.PresentationTimestamps) }).Where(window => window.ProbeSucceeded && window.PresentationTimestamps.Count >= 4).ToArray(); if (samples.Length == 0 || e.NominalFps is not > 0 || e.AverageFps is not > 0) return new(SourceTimingClassification.Unknown, AiTimingEligibility.Unknown, 0, e.NominalFps, e.AverageFps, 0, false, false, "Insufficient timestamp evidence for safe AI eligibility.");
        SourceTimingWindowResult[] windows = samples.Select(Window).ToArray(); bool nonMonotonic = windows.Any(x => x.HasNonMonotonicTimestamps), discontinuity = windows.Any(x => x.HasDiscontinuity); double median = windows.Select(x => x.MedianInterval).OrderBy(x => x).ElementAt(windows.Length / 2); double cadenceVariance = windows.Select(x => Math.Abs(x.MedianInterval - median)).Average() / Math.Max(.000001, median); double intervalVariance = windows.Average(x => x.IntervalVariance); double relative = Math.Max(cadenceVariance, intervalVariance / Math.Max(.000001, median)); bool ratesClose = Math.Abs(e.NominalFps.Value - e.AverageFps.Value) / Math.Max(e.NominalFps.Value, e.AverageFps.Value) < .02;
        SourceTimingClassification classification = nonMonotonic || discontinuity ? SourceTimingClassification.IrregularUnsafe : cadenceVariance > .04 || relative > .08 ? SourceTimingClassification.Vfr : relative > .015 || !ratesClose ? SourceTimingClassification.CfrMinorVariance : SourceTimingClassification.Cfr;
        AiTimingEligibility eligibility = classification == SourceTimingClassification.Cfr ? AiTimingEligibility.EligibleCurrentCfrPipeline : classification is SourceTimingClassification.Vfr or SourceTimingClassification.CfrMinorVariance ? AiTimingEligibility.PotentialFutureTimestampAware : AiTimingEligibility.UnsafeUnsupported;
        string reason = classification == SourceTimingClassification.Cfr ? "Stable sampled CFR cadence is compatible with the current AI pipeline." : classification == SourceTimingClassification.CfrMinorVariance ? "Minor timestamp variance detected; current frame-based AI remains unavailable." : classification == SourceTimingClassification.Vfr ? "Variable frame timing detected; current frame-based AI remains unavailable." : "Timestamp discontinuity or non-monotonic timing detected; AI restoration is unsafe.";
        return new(classification, eligibility, Math.Min(90, 40 + windows.Length * 10), e.NominalFps, e.AverageFps, intervalVariance, discontinuity, nonMonotonic, reason, windows);
    }
    /// <summary>Current AI frame processing is CFR-only. Future VFR research must not bypass this boundary.</summary>
    public static void EnsureCurrentCfrSupported(SourceTimingAnalysis timing)
    {
        if (timing.AiEligibility == AiTimingEligibility.EligibleCurrentCfrPipeline) return;
        throw new AiRestorationValidationException("AI restoration is unavailable for this source timing. Conventional restoration and normal encoding remain available. " + timing.Reason);
    }
    public async Task<SourceTimingAnalysis> AnalyzeAsync(string source, CancellationToken token = default)
    {
        MediaToolProcessResult info = await _runner.RunAsync(new MediaToolProcessRequest { FileName = _ffprobePath, Arguments = new[] { "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=r_frame_rate,avg_frame_rate,time_base,start_time,duration:format=duration,start_time", "-of", "default=noprint_wrappers=1", source }, Timeout = TimeSpan.FromSeconds(20) }, token).ConfigureAwait(false);
        var map = info.StandardOutput.Split('\n').Select(x => x.Split('=', 2)).Where(x => x.Length == 2).GroupBy(x => x[0]).ToDictionary(x => x.Key, x => x.Last()[1], StringComparer.OrdinalIgnoreCase);
        double duration = ParseNumber(map.GetValueOrDefault("duration")) ?? 0; double[] positions = BuildPositions(duration); var windows = new List<TimingWindowEvidence>(); for (int index = 0; index < positions.Length; index++) { token.ThrowIfCancellationRequested(); double at = positions[index] * duration; MediaToolProcessResult sample; try { sample = await _runner.RunAsync(new MediaToolProcessRequest { FileName = _ffprobePath, Arguments = new[] { "-v", "error", "-read_intervals", at.ToString("0.###", CultureInfo.InvariantCulture) + "%+2", "-select_streams", "v:0", "-show_entries", "frame=best_effort_timestamp_time", "-of", "default=noprint_wrappers=1:nokey=1", source }, Timeout = TimeSpan.FromSeconds(12) }, token).ConfigureAwait(false); } catch (OperationCanceledException) { throw; } catch { windows.Add(new(positions[index], Array.Empty<double>(), false)); continue; } double[] timestamps = sample.StandardOutput.Split('\n').Select(x => double.TryParse(x, NumberStyles.Float, CultureInfo.InvariantCulture, out double value) ? value : double.NaN).Where(double.IsFinite).ToArray(); windows.Add(new(positions[index], timestamps, sample.ExitCode == 0 && !sample.TimedOut)); if (timestamps.Length >= 4) { SourceTimingWindowResult summary = Window(windows[^1]); _log?.Invoke($"[Timing] sample {index + 1}/{positions.Length} @ {positions[index]:P0}: frames={summary.FrameCount}; median={summary.MedianInterval:0.######}; variance={summary.IntervalVariance:0.######}; discontinuities={summary.HasDiscontinuity}."); } }
        SourceTimingAnalysis result = Analyze(new(ParseRate(map.GetValueOrDefault("r_frame_rate")), ParseRate(map.GetValueOrDefault("avg_frame_rate")), map.GetValueOrDefault("time_base") ?? "", ParseNumber(map.GetValueOrDefault("start_time")), ParseNumber(map.GetValueOrDefault("duration")), ParseNumber(map.GetValueOrDefault("duration")), Array.Empty<double>(), windows)); _log?.Invoke($"[Timing] nominal={result.NominalFps}; average={result.AverageFps}; variance={result.IntervalVariance:0.######}; classification={result.Classification}; eligibility={result.AiEligibility}."); return result;
    }
    private static double? ParseRate(string? value) { if (string.IsNullOrWhiteSpace(value)) return null; string[] p = value.Split('/'); return p.Length == 2 && double.TryParse(p[0], out double n) && double.TryParse(p[1], out double d) && d != 0 ? n / d : ParseNumber(value); }
    private static double? ParseNumber(string? value) => double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double n) ? n : null;
    internal static double[] BuildPositions(double duration) => duration < 12 ? new[] { .1, .5, .9 } : new[] { .05, .25, .5, .75, .95 };
    private static SourceTimingWindowResult Window(TimingWindowEvidence window) { double[] intervals = window.PresentationTimestamps.Zip(window.PresentationTimestamps.Skip(1), (a, b) => b - a).ToArray(); bool nonMonotonic = intervals.Any(x => x <= 0); double median = intervals.OrderBy(x => x).ElementAt(intervals.Length / 2); double variance = intervals.Select(x => Math.Abs(x - median)).Average(); return new(window.PositionFraction, window.PresentationTimestamps.Count, median, variance, intervals.Any(x => x > Math.Max(median * 3, .5)), nonMonotonic); }
}
